# Preparación del corpus

Una vez se ha llevado a cabo el análisis exploratorio del corpus, es necesario
transformarlo de tal manera que el LLM sea capaz de entenderlo.

Para ello, se llevan a cabo cuatro acciones principales:

1. Carga del corpus: Se carga el corpus y se separa cada ejemplo con el token
   `<|endoftext|>` para que el LLM sepa donde termina cada historia.
2. División del corpus en tokens: Se utiliza el algoritmo byte-pair encoding
   para convertir el texto a token IDs.
3. Sliding window: Se crea un DataLoader capaz de proveer los datos de
   entrenamiento al LLM utilizando la técnica sliding window. Esta técnica
   limita la cantidad de texto que el LLM tiene que "leer" durante el
   entrenamiento, mejorando su eficiencia.
4. Transformación a token embeddings: Se explica como convertir token IDs en
   token embeddings con información posicional.

## Tokenización y sliding window

Se crea el DataSet y el DataLoader para proveer los datos al modelo utilizando
la técnica sliding window.

In [1]:
from datasets import load_dataset
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import PreTrainedTokenizerFast

In [2]:
class TinyDataset(Dataset):
    def __init__(self, window_size, split):
        assert split == "train" or split == "validation"
        self.window_size = window_size

        tokenizer = PreTrainedTokenizerFast.from_pretrained(
            "vuiseng9/bpe-10.0k-tinystories"
        )

        ds = load_dataset("roneneldan/TinyStories", split=split)

        # Pre-tokeniza por lotes. HuggingFace cachea el resultado en disco,
        # por lo que solo se tokeniza en la primera ejecución.
        # Se guarda también n_tokens para evitar tener que leer todas las
        # listas de tokens solo para calcular sus longitudes.
        self.ds = ds.map(
            lambda batch: {
                "tokens": (
                    encoded := tokenizer(
                        [t + "<|endoftext|>" for t in batch["text"]]
                    )["input_ids"]
                ),
                "n_tokens": [len(ids) for ids in encoded],
            },
            batched=True,
            batch_size=1000,
            remove_columns=ds.column_names,
        )

        # Índice acumulativo de longitudes para mapear posición global -> ejemplo.
        # n_tokens es una columna de enteros en Arrow, se lee sin cargar los tokens.
        lengths = np.array(self.ds["n_tokens"])
        self.cumulative_lengths = np.cumsum(lengths)
        self.total_tokens = int(self.cumulative_lengths[-1])

    def __len__(self):
        return self.total_tokens // self.window_size

    def __getitem__(self, index):
        start = index * self.window_size
        end = start + self.window_size + 1  # +1 para el target (y)

        tokens = self._get_token_range(start, end)
        return torch.tensor(tokens[:-1]), torch.tensor(tokens[1:])

    def _get_token_range(self, start, end):
        first = int(np.searchsorted(self.cumulative_lengths, start, side="right"))
        last = int(np.searchsorted(self.cumulative_lengths, end - 1, side="right"))

        tokens = []
        for i in range(first, min(last + 1, len(self.ds))):
            example_tokens = self.ds[i]["tokens"]
            offset = int(self.cumulative_lengths[i - 1]) if i > 0 else 0
            lo = max(0, start - offset)
            hi = min(len(example_tokens), end - offset)
            tokens.extend(example_tokens[lo:hi])

        return tokens

In [3]:
def create_dataloader(split, batch_size, window_size, shuffle=True, drop_last=True, num_workers = 0):
    dataset = TinyDataset(window_size, split)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last, num_workers=num_workers)
    return dataloader

In [4]:
batch_size = 8
window_size = 4

dataloader = create_dataloader("train", batch_size, window_size, shuffle=False, drop_last=False)

In [5]:
dl_iter = iter(dataloader)
x, y = next(dl_iter)
print(f"x:\n{x}")
print(f"y:\n{y}")

x:
tensor([[ 316,  252,   13,  155],
        [ 293,  342,  396,  260],
        [ 491,  155, 3628,  212],
        [ 205,  654,   15,  209],
        [ 599,  200,  178, 2858],
        [ 162,  255,  238,  200],
        [ 683,  200,  178, 2012],
        [  15,  260,  340,  162]])
y:
tensor([[ 252,   13,  155,  293],
        [ 342,  396,  260,  491],
        [ 155, 3628,  212,  205],
        [ 654,   15,  209,  599],
        [ 200,  178, 2858,  162],
        [ 255,  238,  200,  683],
        [ 200,  178, 2012,   15],
        [ 260,  340,  162,  844]])


## Transformación a token embeddings

En esta sección se explica como convertir token IDs en token embeddings con
información posicional.

### Entendiendo el proceso de creación de token embeddings

Entender el proceso de creación de token embeddings es un primer paso
fundamental antes de pasar a la implementación del mecanismo de atención.
Entender este proceso puede ser complicado, por lo que, antes de generar un
código genérico se aborda el problema con ejemplos sencillos:

Se utilizan los siguientes valores como token IDs:

In [6]:
input_ids = torch.tensor([2, 3, 5, 1])

A continuación, se crea el embedding layer.

El embedding layer es parte del LLM, pero para entender como se generan los
token embeddings, se crea un embedding layer con el que experimentar.

Para su creación necesitamos conocer:

- El tamaño del vocabulario: Viene dado por el encoding del tokenizer utilizado
- El tamaño de los token embeddings (`output_dim`)

No obstante, como primera aproximación se usan valores fáciles de comprender:

In [7]:
vocab_size = 6
output_dim = 3

In [8]:
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

Internamente, el embedding layer no es más que una capa de una red neuronal
optimizada para guardar embeddings y recuperarlos usando un índice. O, expresado
de otra manera, como se puede leer en [la documentación](https://docs.pytorch.org/docs/2.12/generated/torch.nn.Embedding.html)
"A simple lookup table that stores embeddings of a fixed dictionary and size".

Por ejemplo, en nuestro caso, el embedding layer está formado por los siguientes
pesos:

In [9]:
embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

Como se puede observar, hay un total de 6 tensores (`vocab_size`) de dimensión 3
(`output_dim`). Por el momento, estos pesos contienen valores aleatorios, pero
más adelante, durante el entrenamiento del LLM, se modificarán.

El embedding layer se puede utilizar para recuperar los embeddings
referenciandolos por su índice, siendo posible recuperar varios de manera
simultanea:

In [10]:
embedding_layer(torch.tensor([3])) # Corresponde al cuarto tensor del embedding layer

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)

In [11]:
embedding_layer(input_ids) # Índices 2, 3, 5 y 1

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)

### Codificando la posición de los embeddings

Una vez queda claro como se crean los embedding tokens y como se utiliza el
embedding layer el siguiente paso es codificar la posición de cada token.

Dos tokens IDs idénticos devolverán el mismo token embedding. Si bien este token
embedding dará información al LLM sobre el significado de la palabra que
representa, el LLM no tendrá forma de saber en qué parte del texto se encuentra
la dicha palabra.

Ilustrando el problema con el embedding layer similar al del apartado anterior:

In [12]:
print(f"Tamaño del vocabulario: {vocab_size}")
print(f"Número de dimensiones de los token embeddings: {output_dim}")

torch.manual_seed(123)
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

Tamaño del vocabulario: 6
Número de dimensiones de los token embeddings: 3


In [13]:
token_embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

In [14]:
print("Dos token IDs idénticos (0 para el ejemplo) devuelven el mismo token embedding:")
print(token_embedding_layer(torch.tensor([0])))
print(token_embedding_layer(torch.tensor([0])))

Dos token IDs idénticos (0 para el ejemplo) devuelven el mismo token embedding:
tensor([[ 0.3374, -0.1778, -0.1690]], grad_fn=<EmbeddingBackward0>)
tensor([[ 0.3374, -0.1778, -0.1690]], grad_fn=<EmbeddingBackward0>)


Por lo tanto, es necesario añadir información adicional al token embedding para
que el modelo sepa en qué posición se encuentra cada token embedding.

Para lograr este objetivo, GPT-2 añade información posicional absoluta a cada
token embedding.


Para ello, utiliza un segundo embedding layer (que también se ajustará durante
el entrenamiento del modelo) del que se extraerán los embeddings posicionales
(`pos_embeddings`):

In [15]:
# Tamaño del contexto: Número de tokens que el modelo puede referenciar
context_length = 4

torch.manual_seed(456)
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [16]:
pos_embedding_layer.weight

Parameter containing:
tensor([[-2.4306,  0.7544,  1.6025],
        [-1.1431, -0.1645,  0.6943],
        [ 1.2980, -0.7403,  1.0322],
        [-0.7191, -0.0373,  0.2765]], requires_grad=True)

In [17]:
torch.arange(context_length)

tensor([0, 1, 2, 3])

In [18]:
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
pos_embeddings

tensor([[-2.4306,  0.7544,  1.6025],
        [-1.1431, -0.1645,  0.6943],
        [ 1.2980, -0.7403,  1.0322],
        [-0.7191, -0.0373,  0.2765]], grad_fn=<EmbeddingBackward0>)

Una vez se tienen los embeddings posicionales (`pos_embeddings`) se sumarán a
los token embeddings para dotarlos de información posicional.

Siguiendo con el ejemplo anterior, podemos ver como gracias a la información
posicional, dos token ID idénticos ya no generan el mismo token embeddings:

In [19]:
print("Dos token IDs idénticos (0 para el ejemplo) devuelven el mismo token embedding:")
print(token_embedding_layer(torch.tensor([0])))
print(token_embedding_layer(torch.tensor([0])))

Dos token IDs idénticos (0 para el ejemplo) devuelven el mismo token embedding:
tensor([[ 0.3374, -0.1778, -0.1690]], grad_fn=<EmbeddingBackward0>)
tensor([[ 0.3374, -0.1778, -0.1690]], grad_fn=<EmbeddingBackward0>)


In [20]:
print("Gracias a la información posicional el modelo puede distinguirlos:")

print("Token ID 0 en la posición 0:")
print(token_embedding_layer(torch.tensor([0])) + pos_embeddings[0])

print("Token ID 0 en la posición 3:")
print(token_embedding_layer(torch.tensor([0])) + pos_embeddings[3])

Gracias a la información posicional el modelo puede distinguirlos:
Token ID 0 en la posición 0:
tensor([[-2.0932,  0.5766,  1.4335]], grad_fn=<AddBackward0>)
Token ID 0 en la posición 3:
tensor([[-0.3818, -0.2151,  0.1076]], grad_fn=<AddBackward0>)
